name: quick_letter_1
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dots_indicator: ^2.1.0
  downloads_path_provider_28: ^0.1.2
  email_validator: ^2.1.17
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_html_to_pdf: ^0.7.0
  flutter_svg: ^1.1.1+1
  google_nav_bar: ^5.0.6
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  lottie: ^2.0.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/animation/
    - assets/svg/
